apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/smartinix/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/smartinix/order-service
  newTag: 1004b7f413ec7e8a7340b4cdd16910d759be0505

replicas:
- count: 1
  name: order-service
