apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/smartinix/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/smartinix/order-service
  newTag: d5a04e2c5b9b8a98cb1b5bfcb122542e096b5bcb

replicas:
- count: 1
  name: order-service
